defmodule PiCodingAgent.ProviderDisplayNames do
  @moduledoc "Human-readable names for provider identifiers."
  def name("anthropic"), do: "Anthropic"
  def name("openai"), do: "OpenAI"
  def name("google"), do: "Google Gemini"
  def name("google-vertex"), do: "Google Vertex AI"
  def name("deepseek"), do: "DeepSeek"
  def name("groq"), do: "Groq"
  def name("openrouter"), do: "OpenRouter"
  def name("together"), do: "Together AI"
  def name("fireworks"), do: "Fireworks AI"
  def name("xai"), do: "xAI (Grok)"
  def name("mistral"), do: "Mistral AI"
  def name("cerebras"), do: "Cerebras"
  def name("nvidia"), do: "NVIDIA NIM"
  def name("huggingface"), do: "HuggingFace"
  def name("github-copilot"), do: "GitHub Copilot"
  def name("perplexity"), do: "Perplexity"
  def name("azure-openai"), do: "Azure OpenAI"
  def name("amazon-bedrock"), do: "AWS Bedrock"
  def name("vercel-ai-gateway"), do: "Vercel AI Gateway"
  def name("cloudflare-workers-ai"), do: "Cloudflare Workers AI"
  def name("cloudflare-ai-gateway"), do: "Cloudflare AI Gateway"
  def name("minimax"), do: "MiniMax"
  def name("moonshotai"), do: "Moonshot AI"
  def name("zai"), do: "Z.AI"
  def name("xiaomi"), do: "Xiaomi"
  def name("kimi-coding"), do: "Kimi Coding"
  def name("opencode"), do: "OpenCode"
  def name("ant-ling"), do: "Ant Ling"
  def name("openai-codex"), do: "OpenAI Codex"
  def name(id), do: id
end
